syslog_async:  Fix -Werror=unused-result compiler warning
There really is no reason to worry further about this result not being
read; this `write()` call is already a last-ditch effort to log to the
console after nothing else work.

    machinetalk/lib/syslog_async.c: In function ‘log_write_async’:
    machinetalk/lib/syslog_async.c:279:4: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
      279 |    write(fd, entries->payload, entries->length + 1);
	  |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~