halmeter, halscope:  Paper over deprecation warnings from gtk2
In Ubuntu Focal, gtk2 headers warn about deprecated declarations.
gtk2 is deprecated anyway, so this patch just papers over that until
someone decides to port these utilities to some other framework.

	    hal/utils/meter.c -o objects/hal/utils/meter.o
    In file included from /usr/include/gtk-2.0/gtk/gtkobject.h:37,
		     from /usr/include/gtk-2.0/gtk/gtkwidget.h:36,
		     from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35,
		     from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
		     from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
		     from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
		     from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
		     from /usr/include/gtk-2.0/gtk/gtk.h:33,
		     from hal/utils/meter.c:66:
    /usr/include/gtk-2.0/gtk/gtktypeutils.h:236:1: error: ‘GTypeDebugFlags’ is deprecated [-Werror=deprecated-declarations]
      236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);
	  | ^~~~