src/configure.ac:  Update python macros and fix for python3
The `cython3` package installs `/usr/bin/cython3`:

    $ ./autogen.sh && ./configure
    checking for cython... no
    configure: error: not found

Remove local `AC_PYTHON_MODULE` macro and replace with
`AX_PYTHON_MODULE` macro from standard `autoconf-archive` package:

https://www.gnu.org/software/autoconf-archive/ax_python_module.html

Move python detection early so `$PYTHON` is set to `python3`; fixes
the `AX_PYTHON_MODULE` macro picking `python` by default and failing:

    checking python module: google.protobuf.descriptor... Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named google.protobuf.descriptor
    no
    configure: error: failed to find required module google.protobuf.descriptor

Fix `AX_PYTHON_DEVEL` macro call and update min. python version

Remove obsolete `configure.ac` macro

Remove m4/ax_python_devel.m4 macros, now standard in the
`autoconf-archive` package.