Fix python3 syntax errors
Discovered by `dh_python3`, these appear to com from the `compileall`
module; representative errors:

    $ python3 -m compileall -d ../tmp .

    Compiling './debian/machinekit-hal/usr/lib/python3/dist-packages/bitfile.py'...
    ***   File "../tmp/bitfile.py", line 56
	def chunkorder(self, (tag, value)):
			     ^
    SyntaxError: invalid syntax

    Compiling './src/machinetalk/msgcomponents/pbring/pbring-demo.py'...
    ***   File "../tmp/pbring-demo.py", line 31
	except Exception,e:
			^
    SyntaxError: invalid syntax

    Compiling './lib/python/linux_event.py'...
    ***   File "../tmp/linux_event.py", line 836
	raise LookupError, (
			 ^
    SyntaxError: invalid syntax

    Compiling './nosetests/test_groups.py'...
    ***   File "../tmp/test_groups.py", line 45
	raise Exception, "should not happen!"
		       ^
    SyntaxError: invalid syntax

    Compiling './scripts/troff-to-asciidoc.py'...
    ***   File "../tmp/troff-to-asciidoc.py", line 6
	print "source  = " + SourceFilePath
			 ^
    SyntaxError: Missing parentheses in call to 'print'

    Compiling './src/machinetalk/config-service/getapp.py'...
    ***   File "../tmp/getapp.py", line 15
	print '  IP         =', socket.inet_ntoa(rdata)
			     ^
    SyntaxError: invalid syntax