hal/user_comps/xhc-whb04b-6:  silence compiler warnings
For some reason the `-pedantic` compiler arg was added on these
sources, and for some reason only the Linaro tool chain (only used in
Jessie armhf builds) gives the following warning:

    In file included from hal/user_comps/xhc-whb04b-6/usb.cc:23:0:
    /usr/include/libusb-1.0/libusb.h:738:4: error: ISO C++ forbids zero-size array ‘dev_capability_data’ [-Werror=pedantic]
      [0] /* non-standard, but usually working code */
        ^